### ISSUE TITLE
Script broken

### ISSUE THREAD

**Issue by epicgamr500** [Exunys/Aimbot-V2#5] opened 2022-05-26 00:30 UTC
I am using KRNL and the script appears to just stop working randomly, is this a bug or just something with me? The other script was very buggy but worked consistently, now this one will randomly not lock onto people but lock onto certain people while if I turn on team check it just breaks completely.

**Comment by Exunys** [comment] 2022-05-29 14:54
Sorry but I sort of did not understand your issue, can you elaborate more if possible? By the way, I haven't heard that other synapse x users experience the same problem. Could be an executor problem, roblox patch or could depend on the game really. I want to learn more about this issue so I can see if its on your part or I have to take action and look into my code and fix any potential bugs. Thank you.

**Comment by Exunys** [comment] 2022-06-07 00:32
After discussing with the user over discord, the problem is sort of hopefully fixed now. I will be staying updated to the script's stability and situation on bugs.

**Closed by Exunys** 2022-06-07 00:32 UTC
